"use strict";
var assert = require("assert");
global.PSettings = require("../js/settings.js");
delete require.cache[require.resolve("../js/ui.settings.js")];
var ui = require("../js/ui.settings.js");
var saved = [];
ui.open(null, function (v) { saved.push(v); });
ui.update({ moveX: 1 });
assert.strictEqual(ui.get().audio.master, 0.9, "right adjusts the selected master bus");
ui.update({ moveX: 0 });
ui.update({ moveD: -1 });
assert.strictEqual(ui.cursor(), 1, "down selects the next row");
ui.update({ moveD: 0 });
ui.update({ moveX: -1 });
assert.strictEqual(ui.get().audio.music, 0.6, "left adjusts music volume");
assert(saved.length >= 2, "changes publish persistence callbacks");
assert.strictEqual(ui.update({ pausePressed: true }).done, true, "pause/back exits settings");
var before = ui.get();
var changed = PSettings.remap(before, "p1", "gamepad", "jump", "Button10");
assert.strictEqual(changed.ok, true, "gamepad remap uses the same conflict-safe settings contract");
console.log("ok settings UI navigation and persistence callbacks");
